use serde::Serialize;

#[derive(Debug, Default, Clone)]
pub(crate) struct Stats {
    pub(crate) orders_received: u64,
    pub(crate) orders_accepted: u64,
    pub(crate) orders_rejected: u64,
    pub(crate) orders_rejected_bad_request: u64,
    pub(crate) orders_rejected_insufficient_balance: u64,
    pub(crate) orders_rejected_stale_balance_cache: u64,
    pub(crate) orders_failed_balance_refresh: u64,
    pub(crate) unique_orders_with_successful_fill: u64,
    pub(crate) order_sides_filled: u64,
    pub(crate) fill_candidates: u64,
    pub(crate) settlements_attempted: u64,
    pub(crate) settlement_tx_attempts: u64,
    pub(crate) settlements_precheck_failed: u64,
    pub(crate) settlement_send_failures: u64,
    pub(crate) settlement_receipt_failures: u64,
    pub(crate) settlements_reverted: u64,
    pub(crate) settlement_unknown_outcomes: u64,
    pub(crate) successful_settlements: u64,
    pub(crate) orders_marked_stale: u64,
    pub(crate) admission_balance_refreshes: u64,
    pub(crate) pre_settlement_balance_refreshes: u64,
    pub(crate) background_balance_refreshes: u64,
    pub(crate) cache_dirty_events: u64,
}

#[derive(Debug, Serialize)]
pub(crate) struct StatsSnapshot {
    pub(crate) orders_received: u64,
    pub(crate) orders_accepted: u64,
    pub(crate) orders_accepted_pct: f64,
    pub(crate) orders_rejected: u64,
    pub(crate) orders_rejected_pct: f64,
    pub(crate) orders_admission_failures: u64,
    pub(crate) orders_admission_failures_pct: f64,
    pub(crate) orders_rejected_bad_request: u64,
    pub(crate) orders_rejected_bad_request_pct: f64,
    pub(crate) orders_rejected_insufficient_balance: u64,
    pub(crate) orders_rejected_insufficient_balance_pct: f64,
    pub(crate) orders_rejected_stale_balance_cache: u64,
    pub(crate) orders_rejected_stale_balance_cache_pct: f64,
    pub(crate) orders_failed_balance_refresh: u64,
    pub(crate) orders_failed_balance_refresh_pct: f64,
    pub(crate) orders_matched: u64,
    pub(crate) orders_with_successful_fill: u64,
    pub(crate) unique_orders_filled: u64,
    pub(crate) unique_orders_filled_pct_of_accepted: f64,
    pub(crate) unique_orders_with_successful_fill: u64,
    pub(crate) order_sides_filled: u64,
    pub(crate) order_fill_side_events: u64,
    pub(crate) order_fill_side_events_per_accepted_order: f64,
    pub(crate) fill_sides_successfully_settled: u64,
    pub(crate) market_ioc_orders_accepted: u64,
    pub(crate) market_ioc_orders_cancelled_unfilled: usize,
    pub(crate) currently_open_market_ioc_orders: usize,
    pub(crate) fill_candidates: u64,
    pub(crate) orders_matched_pct_of_accepted: f64,
    pub(crate) unique_orders_with_successful_fill_pct_of_accepted: f64,
    pub(crate) settlements_attempted: u64,
    pub(crate) settlements_attempted_pct_of_candidates: f64,
    pub(crate) settlement_precheck_attempts: u64,
    pub(crate) settlement_precheck_attempts_pct_of_candidates: f64,
    pub(crate) settlement_precheck_passed: u64,
    pub(crate) settlement_precheck_passed_pct: f64,
    pub(crate) settlement_tx_attempts: u64,
    pub(crate) settlement_tx_attempts_pct_of_attempted: f64,
    pub(crate) settlement_tx_attempts_pct_of_precheck_passed: f64,
    pub(crate) settlement_tx_submitted: u64,
    pub(crate) settlement_tx_submitted_pct_of_attempts: f64,
    pub(crate) settlement_failures: u64,
    pub(crate) settlement_failures_pct: f64,
    pub(crate) settlement_tx_failures: u64,
    pub(crate) settlement_tx_failures_pct: f64,
    pub(crate) settlements_precheck_failed: u64,
    pub(crate) settlement_precheck_failures: u64,
    pub(crate) settlements_precheck_failed_pct: f64,
    pub(crate) settlement_send_failures: u64,
    pub(crate) settlement_send_failures_pct: f64,
    pub(crate) settlement_receipt_failures: u64,
    pub(crate) settlement_receipt_failures_pct: f64,
    pub(crate) settlements_reverted: u64,
    pub(crate) settlement_reverts: u64,
    pub(crate) settlement_receipt_status_reverted: u64,
    pub(crate) settlement_tx_reverts: u64,
    pub(crate) settlement_receipt_successes: u64,
    pub(crate) settlement_terminal_outcomes: u64,
    pub(crate) settlement_pending_outcomes: u64,
    pub(crate) settlement_unknown_outcomes: u64,
    pub(crate) settlements_reverted_pct: f64,
    pub(crate) currently_open_orders: usize,
    pub(crate) currently_open_orders_pct_of_accepted: f64,
    pub(crate) currently_live_orders: usize,
    pub(crate) currently_live_orders_pct_of_accepted: f64,
    pub(crate) currently_open_status_orders: usize,
    pub(crate) currently_partially_filled_orders: usize,
    pub(crate) currently_filled_orders: usize,
    pub(crate) currently_filled_orders_pct_of_accepted: f64,
    pub(crate) currently_cancelled_orders: usize,
    pub(crate) currently_stale_orders: usize,
    pub(crate) currently_stale_orders_pct_of_accepted: f64,
    pub(crate) successful_settlements: u64,
    pub(crate) fills_settled: u64,
    pub(crate) fills_successfully_settled: u64,
    pub(crate) successful_settlements_pct: f64,
    pub(crate) successful_settlements_pct_of_candidates: f64,
    pub(crate) successful_settlements_pct_of_accepted: f64,
    pub(crate) orders_marked_stale: u64,
    pub(crate) orders_marked_stale_pct_of_accepted: f64,
    pub(crate) admission_balance_refreshes: u64,
    pub(crate) pre_settlement_balance_refreshes: u64,
    pub(crate) background_balance_refreshes: u64,
    pub(crate) cache_dirty_events: u64,
    pub(crate) average_active_cache_age_ms: u64,
}

pub(crate) fn pct(numerator: u64, denominator: u64) -> f64 {
    if denominator == 0 {
        0.0
    } else {
        numerator as f64 * 100.0 / denominator as f64
    }
}

pub(crate) fn ratio(numerator: u64, denominator: u64) -> f64 {
    if denominator == 0 {
        0.0
    } else {
        numerator as f64 / denominator as f64
    }
}
